export interface CountryCodeItem {
  name: string;
  code: string; // 2-letter ISO code
  dialCode: string; // e.g. +1, +880
  flag: string; // Emoji flag
  flagUrl: string; // https://flagsapi.com/:code/flat/64.png
}

export function getFlagApiUrl(code: string): string {
  return `https://flagsapi.com/${code.toUpperCase()}/flat/64.png`;
}

export const WORLD_COUNTRY_CODES: CountryCodeItem[] = [
  { name: "Andorra", code: "AD", dialCode: "+376", flag: "🇦🇩", flagUrl: getFlagApiUrl("AD") },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971", flag: "🇦🇪", flagUrl: getFlagApiUrl("AE") },
  { name: "Afghanistan", code: "AF", dialCode: "+93", flag: "🇦🇫", flagUrl: getFlagApiUrl("AF") },
  { name: "Antigua and Barbuda", code: "AG", dialCode: "+1268", flag: "🇦🇬", flagUrl: getFlagApiUrl("AG") },
  { name: "Anguilla", code: "AI", dialCode: "+1264", flag: "🇦🇮", flagUrl: getFlagApiUrl("AI") },
  { name: "Artsakh", code: "AH", dialCode: "+1", flag: "🇦🇭", flagUrl: getFlagApiUrl("AH") },
  { name: "Abkhazia", code: "AK", dialCode: "+1", flag: "🇦🇰", flagUrl: getFlagApiUrl("AK") },
  { name: "Albania", code: "AL", dialCode: "+355", flag: "🇦🇱", flagUrl: getFlagApiUrl("AL") },
  { name: "Armenia", code: "AM", dialCode: "+374", flag: "🇦🇲", flagUrl: getFlagApiUrl("AM") },
  { name: "Netherlands Antilles", code: "AN", dialCode: "+599", flag: "🇦🇳", flagUrl: getFlagApiUrl("AN") },
  { name: "Angola", code: "AO", dialCode: "+244", flag: "🇦🇴", flagUrl: getFlagApiUrl("AO") },
  { name: "Antarctica", code: "AQ", dialCode: "+672", flag: "🇦🇶", flagUrl: getFlagApiUrl("AQ") },
  { name: "Argentina", code: "AR", dialCode: "+54", flag: "🇦🇷", flagUrl: getFlagApiUrl("AR") },
  { name: "American Samoa", code: "AS", dialCode: "+1684", flag: "🇦🇸", flagUrl: getFlagApiUrl("AS") },
  { name: "Austria", code: "AT", dialCode: "+43", flag: "🇦🇹", flagUrl: getFlagApiUrl("AT") },
  { name: "Australia", code: "AU", dialCode: "+61", flag: "🇦🇺", flagUrl: getFlagApiUrl("AU") },
  { name: "Aruba", code: "AW", dialCode: "+297", flag: "🇦🇼", flagUrl: getFlagApiUrl("AW") },
  { name: "Åland Islands", code: "AX", dialCode: "+358", flag: "🇦🇽", flagUrl: getFlagApiUrl("AX") },
  { name: "Azerbaijan", code: "AZ", dialCode: "+994", flag: "🇦🇿", flagUrl: getFlagApiUrl("AZ") },
  { name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387", flag: "🇧🇦", flagUrl: getFlagApiUrl("BA") },
  { name: "Barbados", code: "BB", dialCode: "+1246", flag: "🇧🇧", flagUrl: getFlagApiUrl("BB") },
  { name: "Bangladesh", code: "BD", dialCode: "+880", flag: "🇧🇩", flagUrl: getFlagApiUrl("BD") },
  { name: "Belgium", code: "BE", dialCode: "+32", flag: "🇧🇪", flagUrl: getFlagApiUrl("BE") },
  { name: "Burkina Faso", code: "BF", dialCode: "+226", flag: "🇧🇫", flagUrl: getFlagApiUrl("BF") },
  { name: "Bulgaria", code: "BG", dialCode: "+359", flag: "🇧🇬", flagUrl: getFlagApiUrl("BG") },
  { name: "Bahrain", code: "BH", dialCode: "+973", flag: "🇧🇭", flagUrl: getFlagApiUrl("BH") },
  { name: "Burundi", code: "BI", dialCode: "+257", flag: "🇧🇮", flagUrl: getFlagApiUrl("BI") },
  { name: "Benin", code: "BJ", dialCode: "+229", flag: "🇧🇯", flagUrl: getFlagApiUrl("BJ") },
  { name: "Saint Barthélemy", code: "BL", dialCode: "+590", flag: "🇧🇱", flagUrl: getFlagApiUrl("BL") },
  { name: "Bermuda", code: "BM", dialCode: "+1441", flag: "🇧🇲", flagUrl: getFlagApiUrl("BM") },
  { name: "Brunei Darussalam", code: "BN", dialCode: "+673", flag: "🇧🇳", flagUrl: getFlagApiUrl("BN") },
  { name: "Bolivia", code: "BO", dialCode: "+591", flag: "🇧🇴", flagUrl: getFlagApiUrl("BO") },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ", dialCode: "+599", flag: "🇧🇶", flagUrl: getFlagApiUrl("BQ") },
  { name: "Brazil", code: "BR", dialCode: "+55", flag: "🇧🇷", flagUrl: getFlagApiUrl("BR") },
  { name: "Bahamas", code: "BS", dialCode: "+1242", flag: "🇧🇸", flagUrl: getFlagApiUrl("BS") },
  { name: "Bhutan", code: "BT", dialCode: "+975", flag: "🇧🇹", flagUrl: getFlagApiUrl("BT") },
  { name: "Bouvet Island", code: "BV", dialCode: "+47", flag: "🇧🇻", flagUrl: getFlagApiUrl("BV") },
  { name: "Botswana", code: "BW", dialCode: "+267", flag: "🇧🇼", flagUrl: getFlagApiUrl("BW") },
  { name: "Belarus", code: "BY", dialCode: "+375", flag: "🇧🇾", flagUrl: getFlagApiUrl("BY") },
  { name: "Belize", code: "BZ", dialCode: "+501", flag: "🇧🇿", flagUrl: getFlagApiUrl("BZ") },
  { name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦", flagUrl: getFlagApiUrl("CA") },
  { name: "Cocos (Keeling) Islands", code: "CC", dialCode: "+61", flag: "🇨🇨", flagUrl: getFlagApiUrl("CC") },
  { name: "Congo, The Democratic Republic Of The", code: "CD", dialCode: "+243", flag: "🇨🇩", flagUrl: getFlagApiUrl("CD") },
  { name: "Central African Republic", code: "CF", dialCode: "+236", flag: "🇨🇫", flagUrl: getFlagApiUrl("CF") },
  { name: "Congo", code: "CG", dialCode: "+242", flag: "🇨🇬", flagUrl: getFlagApiUrl("CG") },
  { name: "Switzerland", code: "CH", dialCode: "+41", flag: "🇨🇭", flagUrl: getFlagApiUrl("CH") },
  { name: "Côte D'Ivoire", code: "CI", dialCode: "+225", flag: "🇨🇮", flagUrl: getFlagApiUrl("CI") },
  { name: "Cook Islands", code: "CK", dialCode: "+682", flag: "🇨🇰", flagUrl: getFlagApiUrl("CK") },
  { name: "Chile", code: "CL", dialCode: "+56", flag: "🇨🇱", flagUrl: getFlagApiUrl("CL") },
  { name: "Cameroon", code: "CM", dialCode: "+237", flag: "🇨🇲", flagUrl: getFlagApiUrl("CM") },
  { name: "China", code: "CN", dialCode: "+86", flag: "🇨🇳", flagUrl: getFlagApiUrl("CN") },
  { name: "Colombia", code: "CO", dialCode: "+57", flag: "🇨🇴", flagUrl: getFlagApiUrl("CO") },
  { name: "Costa Rica", code: "CR", dialCode: "+506", flag: "🇨🇷", flagUrl: getFlagApiUrl("CR") },
  { name: "Cuba", code: "CU", dialCode: "+53", flag: "🇨🇺", flagUrl: getFlagApiUrl("CU") },
  { name: "Cape Verde", code: "CV", dialCode: "+238", flag: "🇨🇻", flagUrl: getFlagApiUrl("CV") },
  { name: "Curaçao", code: "CW", dialCode: "+599", flag: "🇨🇼", flagUrl: getFlagApiUrl("CW") },
  { name: "Christmas Island", code: "CX", dialCode: "+61", flag: "🇨🇽", flagUrl: getFlagApiUrl("CX") },
  { name: "Cyprus", code: "CY", dialCode: "+357", flag: "🇨🇾", flagUrl: getFlagApiUrl("CY") },
  { name: "Czech Republic", code: "CZ", dialCode: "+420", flag: "🇨🇿", flagUrl: getFlagApiUrl("CZ") },
  { name: "Germany", code: "DE", dialCode: "+49", flag: "🇩🇪", flagUrl: getFlagApiUrl("DE") },
  { name: "Djibouti", code: "DJ", dialCode: "+253", flag: "🇩🇯", flagUrl: getFlagApiUrl("DJ") },
  { name: "Denmark", code: "DK", dialCode: "+45", flag: "🇩🇰", flagUrl: getFlagApiUrl("DK") },
  { name: "Dominica", code: "DM", dialCode: "+1767", flag: "🇩🇲", flagUrl: getFlagApiUrl("DM") },
  { name: "Dominican Republic", code: "DO", dialCode: "+1809", flag: "🇩🇴", flagUrl: getFlagApiUrl("DO") },
  { name: "Algeria", code: "DZ", dialCode: "+213", flag: "🇩🇿", flagUrl: getFlagApiUrl("DZ") },
  { name: "Ecuador", code: "EC", dialCode: "+593", flag: "🇪🇨", flagUrl: getFlagApiUrl("EC") },
  { name: "Estonia", code: "EE", dialCode: "+372", flag: "🇪🇪", flagUrl: getFlagApiUrl("EE") },
  { name: "Egypt", code: "EG", dialCode: "+20", flag: "🇪🇬", flagUrl: getFlagApiUrl("EG") },
  { name: "Western Sahara", code: "EH", dialCode: "+212", flag: "🇪🇭", flagUrl: getFlagApiUrl("EH") },
  { name: "Eritrea", code: "ER", dialCode: "+291", flag: "🇪🇷", flagUrl: getFlagApiUrl("ER") },
  { name: "Spain", code: "ES", dialCode: "+34", flag: "🇪🇸", flagUrl: getFlagApiUrl("ES") },
  { name: "Ethiopia", code: "ET", dialCode: "+251", flag: "🇪🇹", flagUrl: getFlagApiUrl("ET") },
  { name: "European Union", code: "EU", dialCode: "+1", flag: "🇪🇺", flagUrl: getFlagApiUrl("EU") },
  { name: "Finland", code: "FI", dialCode: "+358", flag: "🇫🇮", flagUrl: getFlagApiUrl("FI") },
  { name: "Fiji", code: "FJ", dialCode: "+679", flag: "🇫🇯", flagUrl: getFlagApiUrl("FJ") },
  { name: "Falkland Islands (Malvinas)", code: "FK", dialCode: "+500", flag: "🇫🇰", flagUrl: getFlagApiUrl("FK") },
  { name: "Micronesia, Federated States Of", code: "FM", dialCode: "+691", flag: "🇫🇲", flagUrl: getFlagApiUrl("FM") },
  { name: "Faroe Islands", code: "FO", dialCode: "+298", flag: "🇫🇴", flagUrl: getFlagApiUrl("FO") },
  { name: "France", code: "FR", dialCode: "+33", flag: "🇫🇷", flagUrl: getFlagApiUrl("FR") },
  { name: "Gabon", code: "GA", dialCode: "+241", flag: "🇬🇦", flagUrl: getFlagApiUrl("GA") },
  { name: "United Kingdom", code: "GB", dialCode: "+44", flag: "🇬🇧", flagUrl: getFlagApiUrl("GB") },
  { name: "Grenada", code: "GD", dialCode: "+1473", flag: "🇬🇩", flagUrl: getFlagApiUrl("GD") },
  { name: "Georgia", code: "GE", dialCode: "+995", flag: "🇬🇪", flagUrl: getFlagApiUrl("GE") },
  { name: "French Guiana", code: "GF", dialCode: "+594", flag: "🇬🇫", flagUrl: getFlagApiUrl("GF") },
  { name: "Guernsey", code: "GG", dialCode: "+44", flag: "🇬🇬", flagUrl: getFlagApiUrl("GG") },
  { name: "Ghana", code: "GH", dialCode: "+233", flag: "🇬🇭", flagUrl: getFlagApiUrl("GH") },
  { name: "Gibraltar", code: "GI", dialCode: "+350", flag: "🇬🇮", flagUrl: getFlagApiUrl("GI") },
  { name: "Greenland", code: "GL", dialCode: "+299", flag: "🇬🇱", flagUrl: getFlagApiUrl("GL") },
  { name: "Gambia", code: "GM", dialCode: "+220", flag: "🇬🇲", flagUrl: getFlagApiUrl("GM") },
  { name: "Guinea", code: "GN", dialCode: "+224", flag: "🇬🇳", flagUrl: getFlagApiUrl("GN") },
  { name: "Guadeloupe", code: "GP", dialCode: "+590", flag: "🇬🇵", flagUrl: getFlagApiUrl("GP") },
  { name: "Equatorial Guinea", code: "GQ", dialCode: "+240", flag: "🇬🇶", flagUrl: getFlagApiUrl("GQ") },
  { name: "Greece", code: "GR", dialCode: "+30", flag: "🇬🇷", flagUrl: getFlagApiUrl("GR") },
  { name: "South Georgia and the South Sandwich Islands", code: "GS", dialCode: "+500", flag: "🇬🇸", flagUrl: getFlagApiUrl("GS") },
  { name: "Guatemala", code: "GT", dialCode: "+502", flag: "🇬🇹", flagUrl: getFlagApiUrl("GT") },
  { name: "Guam", code: "GU", dialCode: "+1671", flag: "🇬🇺", flagUrl: getFlagApiUrl("GU") },
  { name: "Guinea-Bissau", code: "GW", dialCode: "+245", flag: "🇬🇼", flagUrl: getFlagApiUrl("GW") },
  { name: "Guyana", code: "GY", dialCode: "+592", flag: "🇬🇾", flagUrl: getFlagApiUrl("GY") },
  { name: "Hong Kong", code: "HK", dialCode: "+852", flag: "🇭🇰", flagUrl: getFlagApiUrl("HK") },
  { name: "Heard and McDonald Islands", code: "HM", dialCode: "+672", flag: "🇭🇲", flagUrl: getFlagApiUrl("HM") },
  { name: "Honduras", code: "HN", dialCode: "+504", flag: "🇭🇳", flagUrl: getFlagApiUrl("HN") },
  { name: "Croatia", code: "HR", dialCode: "+385", flag: "🇭🇷", flagUrl: getFlagApiUrl("HR") },
  { name: "Haiti", code: "HT", dialCode: "+509", flag: "🇭🇹", flagUrl: getFlagApiUrl("HT") },
  { name: "Hungary", code: "HU", dialCode: "+36", flag: "🇭🇺", flagUrl: getFlagApiUrl("HU") },
  { name: "Canary Islands", code: "IC", dialCode: "+1", flag: "🇮🇨", flagUrl: getFlagApiUrl("IC") },
  { name: "Indonesia", code: "ID", dialCode: "+62", flag: "🇮🇩", flagUrl: getFlagApiUrl("ID") },
  { name: "Ireland", code: "IE", dialCode: "+353", flag: "🇮🇪", flagUrl: getFlagApiUrl("IE") },
  { name: "Israel", code: "IL", dialCode: "+972", flag: "🇮🇱", flagUrl: getFlagApiUrl("IL") },
  { name: "Isle of Man", code: "IM", dialCode: "+44", flag: "🇮🇲", flagUrl: getFlagApiUrl("IM") },
  { name: "India", code: "IN", dialCode: "+91", flag: "🇮🇳", flagUrl: getFlagApiUrl("IN") },
  { name: "British Indian Ocean Territory", code: "IO", dialCode: "+246", flag: "🇮🇴", flagUrl: getFlagApiUrl("IO") },
  { name: "Iraq", code: "IQ", dialCode: "+964", flag: "🇮🇶", flagUrl: getFlagApiUrl("IQ") },
  { name: "Iran, Islamic Republic Of", code: "IR", dialCode: "+98", flag: "🇮🇷", flagUrl: getFlagApiUrl("IR") },
  { name: "Iceland", code: "IS", dialCode: "+354", flag: "🇮🇸", flagUrl: getFlagApiUrl("IS") },
  { name: "Italy", code: "IT", dialCode: "+39", flag: "🇮🇹", flagUrl: getFlagApiUrl("IT") },
  { name: "Jersey", code: "JE", dialCode: "+44", flag: "🇯🇪", flagUrl: getFlagApiUrl("JE") },
  { name: "Jamaica", code: "JM", dialCode: "+1876", flag: "🇯🇲", flagUrl: getFlagApiUrl("JM") },
  { name: "Jordan", code: "JO", dialCode: "+962", flag: "🇯🇴", flagUrl: getFlagApiUrl("JO") },
  { name: "Japan", code: "JP", dialCode: "+81", flag: "🇯🇵", flagUrl: getFlagApiUrl("JP") },
  { name: "Kenya", code: "KE", dialCode: "+254", flag: "🇰🇪", flagUrl: getFlagApiUrl("KE") },
  { name: "Kyrgyzstan", code: "KG", dialCode: "+996", flag: "🇰🇬", flagUrl: getFlagApiUrl("KG") },
  { name: "Cambodia", code: "KH", dialCode: "+855", flag: "🇰🇭", flagUrl: getFlagApiUrl("KH") },
  { name: "Kiribati", code: "KI", dialCode: "+686", flag: "🇰🇮", flagUrl: getFlagApiUrl("KI") },
  { name: "Comoros", code: "KM", dialCode: "+269", flag: "🇰🇲", flagUrl: getFlagApiUrl("KM") },
  { name: "Saint Kitts And Nevis", code: "KN", dialCode: "+1869", flag: "🇰🇳", flagUrl: getFlagApiUrl("KN") },
  { name: "Korea, Democratic People's Republic Of", code: "KP", dialCode: "+850", flag: "🇰🇵", flagUrl: getFlagApiUrl("KP") },
  { name: "Korea, Republic of", code: "KR", dialCode: "+82", flag: "🇰🇷", flagUrl: getFlagApiUrl("KR") },
  { name: "Kuwait", code: "KW", dialCode: "+965", flag: "🇰🇼", flagUrl: getFlagApiUrl("KW") },
  { name: "Cayman Islands", code: "KY", dialCode: "+1345", flag: "🇰🇾", flagUrl: getFlagApiUrl("KY") },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: "🇰🇿", flagUrl: getFlagApiUrl("KZ") },
  { name: "Lao People's Democratic Republic", code: "LA", dialCode: "+856", flag: "🇱🇦", flagUrl: getFlagApiUrl("LA") },
  { name: "Lebanon", code: "LB", dialCode: "+961", flag: "🇱🇧", flagUrl: getFlagApiUrl("LB") },
  { name: "Saint Lucia", code: "LC", dialCode: "+1758", flag: "🇱🇨", flagUrl: getFlagApiUrl("LC") },
  { name: "Liechtenstein", code: "LI", dialCode: "+423", flag: "🇱🇮", flagUrl: getFlagApiUrl("LI") },
  { name: "Sri Lanka", code: "LK", dialCode: "+94", flag: "🇱🇰", flagUrl: getFlagApiUrl("LK") },
  { name: "Liberia", code: "LR", dialCode: "+231", flag: "🇱🇷", flagUrl: getFlagApiUrl("LR") },
  { name: "Lesotho", code: "LS", dialCode: "+266", flag: "🇱🇸", flagUrl: getFlagApiUrl("LS") },
  { name: "Lithuania", code: "LT", dialCode: "+370", flag: "🇱🇹", flagUrl: getFlagApiUrl("LT") },
  { name: "Luxembourg", code: "LU", dialCode: "+352", flag: "🇱🇺", flagUrl: getFlagApiUrl("LU") },
  { name: "Latvia", code: "LV", dialCode: "+371", flag: "🇱🇻", flagUrl: getFlagApiUrl("LV") },
  { name: "Libya", code: "LY", dialCode: "+218", flag: "🇱🇾", flagUrl: getFlagApiUrl("LY") },
  { name: "Morocco", code: "MA", dialCode: "+212", flag: "🇲🇦", flagUrl: getFlagApiUrl("MA") },
  { name: "Monaco", code: "MC", dialCode: "+377", flag: "🇲🇨", flagUrl: getFlagApiUrl("MC") },
  { name: "Moldova, Republic of", code: "MD", dialCode: "+373", flag: "🇲🇩", flagUrl: getFlagApiUrl("MD") },
  { name: "Montenegro", code: "ME", dialCode: "+382", flag: "🇲🇪", flagUrl: getFlagApiUrl("ME") },
  { name: "Saint Martin", code: "MF", dialCode: "+590", flag: "🇲🇫", flagUrl: getFlagApiUrl("MF") },
  { name: "Madagascar", code: "MG", dialCode: "+261", flag: "🇲🇬", flagUrl: getFlagApiUrl("MG") },
  { name: "Marshall Islands", code: "MH", dialCode: "+692", flag: "🇲🇭", flagUrl: getFlagApiUrl("MH") },
  { name: "Macedonia, the Former Yugoslav Republic Of", code: "MK", dialCode: "+389", flag: "🇲🇰", flagUrl: getFlagApiUrl("MK") },
  { name: "Mali", code: "ML", dialCode: "+223", flag: "🇲🇱", flagUrl: getFlagApiUrl("ML") },
  { name: "Myanmar", code: "MM", dialCode: "+95", flag: "🇲🇲", flagUrl: getFlagApiUrl("MM") },
  { name: "Mongolia", code: "MN", dialCode: "+976", flag: "🇲🇳", flagUrl: getFlagApiUrl("MN") },
  { name: "Macao", code: "MO", dialCode: "+853", flag: "🇲🇴", flagUrl: getFlagApiUrl("MO") },
  { name: "Northern Mariana Islands", code: "MP", dialCode: "+1670", flag: "🇲🇵", flagUrl: getFlagApiUrl("MP") },
  { name: "Martinique", code: "MQ", dialCode: "+596", flag: "🇲🇶", flagUrl: getFlagApiUrl("MQ") },
  { name: "Mauritania", code: "MR", dialCode: "+222", flag: "🇲🇷", flagUrl: getFlagApiUrl("MR") },
  { name: "Montserrat", code: "MS", dialCode: "+1664", flag: "🇲🇸", flagUrl: getFlagApiUrl("MS") },
  { name: "Malta", code: "MT", dialCode: "+356", flag: "🇲🇹", flagUrl: getFlagApiUrl("MT") },
  { name: "Mauritius", code: "MU", dialCode: "+230", flag: "🇲🇺", flagUrl: getFlagApiUrl("MU") },
  { name: "Maldives", code: "MV", dialCode: "+960", flag: "🇲🇻", flagUrl: getFlagApiUrl("MV") },
  { name: "Malawi", code: "MW", dialCode: "+265", flag: "🇲🇼", flagUrl: getFlagApiUrl("MW") },
  { name: "Mexico", code: "MX", dialCode: "+52", flag: "🇲🇽", flagUrl: getFlagApiUrl("MX") },
  { name: "Malaysia", code: "MY", dialCode: "+60", flag: "🇲🇾", flagUrl: getFlagApiUrl("MY") },
  { name: "Mozambique", code: "MZ", dialCode: "+258", flag: "🇲🇿", flagUrl: getFlagApiUrl("MZ") },
  { name: "Namibia", code: "NA", dialCode: "+264", flag: "🇳🇦", flagUrl: getFlagApiUrl("NA") },
  { name: "New Caledonia", code: "NC", dialCode: "+687", flag: "🇳🇨", flagUrl: getFlagApiUrl("NC") },
  { name: "Niger", code: "NE", dialCode: "+227", flag: "🇳🇪", flagUrl: getFlagApiUrl("NE") },
  { name: "Norfolk Island", code: "NF", dialCode: "+672", flag: "🇳🇫", flagUrl: getFlagApiUrl("NF") },
  { name: "Nigeria", code: "NG", dialCode: "+234", flag: "🇳🇬", flagUrl: getFlagApiUrl("NG") },
  { name: "Nicaragua", code: "NI", dialCode: "+505", flag: "🇳🇮", flagUrl: getFlagApiUrl("NI") },
  { name: "Netherlands", code: "NL", dialCode: "+31", flag: "🇳🇱", flagUrl: getFlagApiUrl("NL") },
  { name: "Norway", code: "NO", dialCode: "+47", flag: "🇳🇴", flagUrl: getFlagApiUrl("NO") },
  { name: "Nepal", code: "NP", dialCode: "+977", flag: "🇳🇵", flagUrl: getFlagApiUrl("NP") },
  { name: "Nauru", code: "NR", dialCode: "+674", flag: "🇳🇷", flagUrl: getFlagApiUrl("NR") },
  { name: "Niue", code: "NU", dialCode: "+683", flag: "🇳🇺", flagUrl: getFlagApiUrl("NU") },
  { name: "Northern Cyprus", code: "NY", dialCode: "+1", flag: "🇳🇾", flagUrl: getFlagApiUrl("NY") },
  { name: "New Zealand", code: "NZ", dialCode: "+64", flag: "🇳🇿", flagUrl: getFlagApiUrl("NZ") },
  { name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲", flagUrl: getFlagApiUrl("OM") },
  { name: "Panama", code: "PA", dialCode: "+507", flag: "🇵🇦", flagUrl: getFlagApiUrl("PA") },
  { name: "Peru", code: "PE", dialCode: "+51", flag: "🇵🇪", flagUrl: getFlagApiUrl("PE") },
  { name: "French Polynesia", code: "PF", dialCode: "+689", flag: "🇵🇫", flagUrl: getFlagApiUrl("PF") },
  { name: "Papua New Guinea", code: "PG", dialCode: "+675", flag: "🇵🇬", flagUrl: getFlagApiUrl("PG") },
  { name: "Philippines", code: "PH", dialCode: "+63", flag: "🇵🇭", flagUrl: getFlagApiUrl("PH") },
  { name: "Pakistan", code: "PK", dialCode: "+92", flag: "🇵🇰", flagUrl: getFlagApiUrl("PK") },
  { name: "Poland", code: "PL", dialCode: "+48", flag: "🇵🇱", flagUrl: getFlagApiUrl("PL") },
  { name: "Saint Pierre And Miquelon", code: "PM", dialCode: "+508", flag: "🇵🇲", flagUrl: getFlagApiUrl("PM") },
  { name: "Pitcairn", code: "PN", dialCode: "+870", flag: "🇵🇳", flagUrl: getFlagApiUrl("PN") },
  { name: "Puerto Rico", code: "PR", dialCode: "+1787", flag: "🇵🇷", flagUrl: getFlagApiUrl("PR") },
  { name: "Palestine, State of", code: "PS", dialCode: "+970", flag: "🇵🇸", flagUrl: getFlagApiUrl("PS") },
  { name: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹", flagUrl: getFlagApiUrl("PT") },
  { name: "Palau", code: "PW", dialCode: "+680", flag: "🇵🇼", flagUrl: getFlagApiUrl("PW") },
  { name: "Paraguay", code: "PY", dialCode: "+595", flag: "🇵🇾", flagUrl: getFlagApiUrl("PY") },
  { name: "Qatar", code: "QA", dialCode: "+974", flag: "🇶🇦", flagUrl: getFlagApiUrl("QA") },
  { name: "Réunion", code: "RE", dialCode: "+262", flag: "🇷🇪", flagUrl: getFlagApiUrl("RE") },
  { name: "Romania", code: "RO", dialCode: "+40", flag: "🇷🇴", flagUrl: getFlagApiUrl("RO") },
  { name: "Serbia", code: "RS", dialCode: "+381", flag: "🇷🇸", flagUrl: getFlagApiUrl("RS") },
  { name: "Russian Federation", code: "RU", dialCode: "+7", flag: "🇷🇺", flagUrl: getFlagApiUrl("RU") },
  { name: "Rwanda", code: "RW", dialCode: "+250", flag: "🇷🇼", flagUrl: getFlagApiUrl("RW") },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966", flag: "🇸🇦", flagUrl: getFlagApiUrl("SA") },
  { name: "Solomon Islands", code: "SB", dialCode: "+677", flag: "🇸🇧", flagUrl: getFlagApiUrl("SB") },
  { name: "Seychelles", code: "SC", dialCode: "+248", flag: "🇸🇨", flagUrl: getFlagApiUrl("SC") },
  { name: "Sudan", code: "SD", dialCode: "+249", flag: "🇸🇩", flagUrl: getFlagApiUrl("SD") },
  { name: "Sweden", code: "SE", dialCode: "+46", flag: "🇸🇪", flagUrl: getFlagApiUrl("SE") },
  { name: "Singapore", code: "SG", dialCode: "+65", flag: "🇸🇬", flagUrl: getFlagApiUrl("SG") },
  { name: "Saint Helena", code: "SH", dialCode: "+290", flag: "🇸🇭", flagUrl: getFlagApiUrl("SH") },
  { name: "Slovenia", code: "SI", dialCode: "+386", flag: "🇸🇮", flagUrl: getFlagApiUrl("SI") },
  { name: "Svalbard And Jan Mayen", code: "SJ", dialCode: "+47", flag: "🇸🇯", flagUrl: getFlagApiUrl("SJ") },
  { name: "Slovakia", code: "SK", dialCode: "+421", flag: "🇸🇰", flagUrl: getFlagApiUrl("SK") },
  { name: "Sierra Leone", code: "SL", dialCode: "+232", flag: "🇸🇱", flagUrl: getFlagApiUrl("SL") },
  { name: "San Marino", code: "SM", dialCode: "+378", flag: "🇸🇲", flagUrl: getFlagApiUrl("SM") },
  { name: "Senegal", code: "SN", dialCode: "+221", flag: "🇸🇳", flagUrl: getFlagApiUrl("SN") },
  { name: "Somalia", code: "SO", dialCode: "+252", flag: "🇸🇴", flagUrl: getFlagApiUrl("SO") },
  { name: "Suriname", code: "SR", dialCode: "+597", flag: "🇸🇷", flagUrl: getFlagApiUrl("SR") },
  { name: "South Sudan", code: "SS", dialCode: "+211", flag: "🇸🇸", flagUrl: getFlagApiUrl("SS") },
  { name: "Sao Tome and Principe", code: "ST", dialCode: "+239", flag: "🇸🇹", flagUrl: getFlagApiUrl("ST") },
  { name: "El Salvador", code: "SV", dialCode: "+503", flag: "🇸🇻", flagUrl: getFlagApiUrl("SV") },
  { name: "Sint Maarten", code: "SX", dialCode: "+1721", flag: "🇸🇽", flagUrl: getFlagApiUrl("SX") },
  { name: "Syrian Arab Republic", code: "SY", dialCode: "+963", flag: "🇸🇾", flagUrl: getFlagApiUrl("SY") },
  { name: "Swaziland", code: "SZ", dialCode: "+268", flag: "🇸🇿", flagUrl: getFlagApiUrl("SZ") },
  { name: "Turks and Caicos Islands", code: "TC", dialCode: "+1649", flag: "🇹🇨", flagUrl: getFlagApiUrl("TC") },
  { name: "Chad", code: "TD", dialCode: "+235", flag: "🇹🇩", flagUrl: getFlagApiUrl("TD") },
  { name: "French Southern Territories", code: "TF", dialCode: "+262", flag: "🇹🇫", flagUrl: getFlagApiUrl("TF") },
  { name: "Togo", code: "TG", dialCode: "+228", flag: "🇹🇬", flagUrl: getFlagApiUrl("TG") },
  { name: "Thailand", code: "TH", dialCode: "+66", flag: "🇹🇭", flagUrl: getFlagApiUrl("TH") },
  { name: "Tajikistan", code: "TJ", dialCode: "+992", flag: "🇹🇯", flagUrl: getFlagApiUrl("TJ") },
  { name: "Tokelau", code: "TK", dialCode: "+690", flag: "🇹🇰", flagUrl: getFlagApiUrl("TK") },
  { name: "Timor-Leste", code: "TL", dialCode: "+670", flag: "🇹🇱", flagUrl: getFlagApiUrl("TL") },
  { name: "Turkmenistan", code: "TM", dialCode: "+993", flag: "🇹🇲", flagUrl: getFlagApiUrl("TM") },
  { name: "Tunisia", code: "TN", dialCode: "+216", flag: "🇹🇳", flagUrl: getFlagApiUrl("TN") },
  { name: "Tonga", code: "TO", dialCode: "+676", flag: "🇹🇴", flagUrl: getFlagApiUrl("TO") },
  { name: "Turkey", code: "TR", dialCode: "+90", flag: "🇹🇷", flagUrl: getFlagApiUrl("TR") },
  { name: "Trinidad and Tobago", code: "TT", dialCode: "+1868", flag: "🇹🇹", flagUrl: getFlagApiUrl("TT") },
  { name: "Tuvalu", code: "TV", dialCode: "+688", flag: "🇹🇻", flagUrl: getFlagApiUrl("TV") },
  { name: "Taiwan, Republic Of China", code: "TW", dialCode: "+886", flag: "🇹🇼", flagUrl: getFlagApiUrl("TW") },
  { name: "Tanzania, United Republic of", code: "TZ", dialCode: "+255", flag: "🇹🇿", flagUrl: getFlagApiUrl("TZ") },
  { name: "Ukraine", code: "UA", dialCode: "+380", flag: "🇺🇦", flagUrl: getFlagApiUrl("UA") },
  { name: "Uganda", code: "UG", dialCode: "+256", flag: "🇺🇬", flagUrl: getFlagApiUrl("UG") },
  { name: "United States Minor Outlying Islands", code: "UM", dialCode: "+1", flag: "🇺🇲", flagUrl: getFlagApiUrl("UM") },
  { name: "United States", code: "US", dialCode: "+1", flag: "🇺🇸", flagUrl: getFlagApiUrl("US") },
  { name: "Uruguay", code: "UY", dialCode: "+598", flag: "🇺🇾", flagUrl: getFlagApiUrl("UY") },
  { name: "Uzbekistan", code: "UZ", dialCode: "+998", flag: "🇺🇿", flagUrl: getFlagApiUrl("UZ") },
  { name: "Holy See (Vatican City State)", code: "VA", dialCode: "+39", flag: "🇻🇦", flagUrl: getFlagApiUrl("VA") },
  { name: "Saint Vincent And The Grenadines", code: "VC", dialCode: "+1784", flag: "🇻🇨", flagUrl: getFlagApiUrl("VC") },
  { name: "Venezuela, Bolivarian Republic of", code: "VE", dialCode: "+58", flag: "🇻🇪", flagUrl: getFlagApiUrl("VE") },
  { name: "Virgin Islands, British", code: "VG", dialCode: "+1284", flag: "🇻🇬", flagUrl: getFlagApiUrl("VG") },
  { name: "Virgin Islands, U.S.", code: "VI", dialCode: "+1340", flag: "🇻🇮", flagUrl: getFlagApiUrl("VI") },
  { name: "Vietnam", code: "VN", dialCode: "+84", flag: "🇻🇳", flagUrl: getFlagApiUrl("VN") },
  { name: "Vanuatu", code: "VU", dialCode: "+678", flag: "🇻🇺", flagUrl: getFlagApiUrl("VU") },
  { name: "Wallis and Futuna", code: "WF", dialCode: "+681", flag: "🇼🇫", flagUrl: getFlagApiUrl("WF") },
  { name: "Samoa", code: "WS", dialCode: "+685", flag: "🇼🇸", flagUrl: getFlagApiUrl("WS") },
  { name: "Kosovo", code: "XK", dialCode: "+383", flag: "🇽🇰", flagUrl: getFlagApiUrl("XK") },
  { name: "Yemen", code: "YE", dialCode: "+967", flag: "🇾🇪", flagUrl: getFlagApiUrl("YE") },
  { name: "Mayotte", code: "YT", dialCode: "+262", flag: "🇾🇹", flagUrl: getFlagApiUrl("YT") },
  { name: "South Africa", code: "ZA", dialCode: "+27", flag: "🇿🇦", flagUrl: getFlagApiUrl("ZA") },
  { name: "Zambia", code: "ZM", dialCode: "+260", flag: "🇿🇲", flagUrl: getFlagApiUrl("ZM") },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263", flag: "🇿🇼", flagUrl: getFlagApiUrl("ZW") },
];
